ambiata/ambiata-cli

.gitmodules, ambiata-cli.cabal, src/Ambiata/Cli.hs, src/Ambiata/Cli/Data.hs, src/Ambiata/Cli/Downloads.hs, src/Ambiata/Cli/Json.hs, src/Ambiata/Cli/Processing.hs, test/Test/IO/Ambiata/Cli/Downloads.hs, test/Test/IO/Ambiata/Cli/Processing.hs
/cc @nhibberd This was quite a big upgrade
=> Upgrade mismi with amazonka 1.3.2.1

ambiata-cli.cabal, test/Test/Ambiata/Cli.hs, test/Test/Cli/Ambiata/Cli/Linking.hs, test/test-cli.hs
=> Add test for static linking of libgmp

.gitmodules, ambiata-cli.cabal, src/Ambiata/Cli/Credentials.hs, src/Ambiata/Cli/Http.hs, test/Test/IO/Ambiata/Cli/Credentials.hs, test/Test/IO/Ambiata/Cli/Http.hs
=> Remove dependency on snooze

ambiata-cli.cabal, src/Ambiata/Cli/Processing.hs
/cc @nhibberd as discussed IRL
=> Bump upload retry to 10 times

src/Ambiata/Cli/Data.hs, src/Ambiata/Cli/Downloads.hs, src/Ambiata/Cli/Processing.hs
=> Upgrade mismi and add AWS debugging

ambiata-cli.cabal, src/Ambiata/Cli/Data.hs, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Data/Download.hs, src/Ambiata/Cli/Data/Env.hs, src/Ambiata/Cli/Data/File.hs, src/Ambiata/Cli/Data/Transfer.hs, src/Ambiata/Cli/Data/Upload.hs, src/Ambiata/Cli/Downloads.hs, src/Ambiata/Cli/Incoming.hs, src/Ambiata/Cli/Json.hs, src/Ambiata/Cli/Json/Upload.hs, src/Ambiata/Cli/Processing.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/IO/Ambiata/Cli/Api/Upload.hs, test/Test/IO/Ambiata/Cli/Processing.hs
/cc @nhibberd @tmcgilchrist 
_Nothing_ changed here, just shuffling code. As always, module naming suggestions welcome.
=> Split Data in to logical modules

doc/setup.md, doc/upload.md
I wasn't sure how much we should provide linking between files (and even how do that nicely in markdown with different output formats)
=> Split upload.md and create common setup.md

ambiata-cli.cabal, doc/download.md, main/ambiata.hs, src/Ambiata/Cli.hs, src/Ambiata/Cli/Api/Download.hs, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Data/Download.hs, src/Ambiata/Cli/Data/Transfer.hs, src/Ambiata/Cli/Downloads.hs, src/Ambiata/Cli/Env.hs, src/Ambiata/Cli/Json/Download.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/Ambiata/Cli/Json.hs, test/Test/IO/Ambiata/Cli/Downloads.hs
This is a naive implementation. I'm going to add support for persistent markers in a separate PR.
/cc @nhibberd @tmcgilchrist 
Grab me if you want to go through a quick conceptual clarify of this.
=> Support simple download

main/ambiata.hs, src/Ambiata/Cli/Data.hs, src/Ambiata/Cli/Data/Download.hs, src/Ambiata/Cli/Downloads.hs, test/Test/IO/Ambiata/Cli/Downloads.hs
=> Introduce marker files for download

ambiata-cli.cabal, bin/bdist, bin/publish, doc/download.md, doc/setup.md, doc/upload.md, main/ambiata-daemon.hs, test/cli/core/runner.sh, test/test-cli.hs
/cc @markhibberd As discussed. Is there anything else we would need to do first?
=> Rename ambiata to ambiata-daemon

doc/examples/ambiata-upload.service, doc/examples/run_ambiata_upload.sh
/cc @markhibberd Whoops, missed these. Not sure if these are critical.
=> Fix examples to point to ambiata-daemon

ambiata-cli.cabal, bin/ci.farm, main/ambiata-daemon.hs
Improved version of https://github.com/ambiata/ambiata-cli/pull/23
=> Add version and dry-run.

ambiata-cli.cabal, doc/setup.md, mafia, main/ambiata.hs, src/Ambiata/Cli.hs, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Data/Env.hs, src/Ambiata/Cli/Env.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/Ambiata/Cli/Data.hs
(and corresponding us-east-1 aws region).
@nhibberd @olorin
=> Allow for ambiata-us endpoint.

.gitmodules, ambiata-cli.cabal, ambiata-cli.lock-7.10.2, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Env.hs, src/Ambiata/Cli/Standalone.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/IO/Ambiata/Cli/Env.hs
Nothing hooked up to them yet, so no behavioural changes as a whole.
After discussion with @markhibberd, we will do a hard switch from hashed credentials to TSRP credentials to force people to migrate, so no need to support both.
Also flesh out/update tests for the old env parsing.
! @charleso
=> Add TSRP env parsers

ambiata-cli.cabal, doc/examples/ambiata-upload.service, doc/examples/run_ambiata_upload.sh, doc/setup.md, main/ambiata.hs, src/Ambiata/Cli.hs, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Data/Download.hs, src/Ambiata/Cli/Data/Env.hs, src/Ambiata/Cli/Data/Upload.hs, src/Ambiata/Cli/Env.hs, src/Ambiata/Cli/Rest.hs, src/Ambiata/Cli/Standalone.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/IO/Ambiata/Cli/Api/Upload.hs, test/Test/IO/Ambiata/Cli/Env.hs
=> Switch to TSRP authentication

src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Data/Env.hs, test/Test/Ambiata/Cli/Arbitrary.hs
=> Replace test Show orphans with redacted instances

bin/publish-docs-dispensary
assume this is ok, as same script uses `spoke`.
! @olorin @nhibberd
=> use s3 upload instead of awscli

test/Test/Cli/Ambiata/Cli/Linking.hs
Bump tinfoil to avoid pulling in libsodium. Also better test for
future borking.
Fixes #59.
Fixes #60.
! @charleso @erikd-ambiata
=> Fix borked linking

src/Ambiata/Cli/Data/Env.hs
=> Adding singapore endpoint support

doc/examples/systemd/ambiata-download.service, doc/examples/systemd/ambiata-upload.service, doc/examples/sysvinit/start-download-example, doc/examples/sysvinit/start-upload-example, doc/examples/upstart/ambiata-download.conf, doc/examples/upstart/ambiata-upload.conf
! @olorin 
/jury approve @olorin @ambiata-ci
=> A few more improvements based on feedback.

ambiata-cli.cabal, bin/bdist
=> Fix build from license change.

doc/examples/raw/run_ambiata_upload.sh, doc/examples/systemd/ambiata-download.service, doc/examples/systemd/ambiata-upload.service, doc/examples/sysvinit/start-download-example, doc/examples/sysvinit/start-upload-example, doc/examples/upstart/ambiata-download.conf, doc/examples/upstart/ambiata-upload.conf, doc/setup.md, src/Ambiata/Cli/Data/Api.hs, src/Ambiata/Cli/Env.hs, src/Ambiata/Cli/Rest.hs, test/Test/Ambiata/Cli/Arbitrary.hs, test/Test/IO/Ambiata/Cli/Env.hs
! @sphvn @nhibberd 
/jury approved @sphvn
=> Re-add support for single token keys
